# 示例面板配置：用于终端 UI 构建程序化请求
# id: 面板唯一标识
# title: 面板显示标题（中文）
# description: 面板简要说明（中文）
# fields: 面板字段定义列表，每个字段用于构建请求参数
#   name: 字段名（请求 key）
#   type: 支持 string / integer / boolean / select
#   label: 中文显示标签
#   placeholder: 占位提示
#   required: 是否必填（true/false）
#   options: 当 type == select 时，列出可选项
# default_values: 示例默认值，用于预填充请求示例

id: example_panel
title: "示例程序化请求面板"
description: "此面板为终端 UI 提供的示例配置，演示如何构建程序化请求参数。"

fields:
  - name: action
    type: select
    label: "操作"
    placeholder: "请选择操作类型"
    required: true
    options:
      - create
      - update
      - delete
      - query
  - name: target
    type: string
    label: "目标"
    placeholder: "填写目标资源标识（例如：user/123）"
    required: true
  - name: count
    type: integer
    label: "数量"
    placeholder: "填写数量（整数）"
    required: false
  - name: verbose
    type: boolean
    label: "详细模式"
    placeholder: "是否输出详细信息（true/false）"
    required: false

# 示例默认值，用于面板打开时预填充并作为请求示例参考
default_values:
  action: query
  target: "user/123"
  count: 1
  verbose: false