id: "example_command"
type: "form"
title: "示例命令：创建任务"
description: "通过表单创建一个任务的示例配置"
autocomplete:
  cacheTTL: 300
  threshold: 1
priority: 10
formSchema:
  fields:
    - name: "title"
      type: "text"
      label: "任务标题"
      placeholder: "输入任务标题"
      required: true
      default: ""
      validation:
        maxLength: 120
    - name: "estimate_hours"
      type: "number"
      label: "预估工时"
      placeholder: "请输入小时数"
      required: false
      default: 1
      validation:
        min: 0
        max: 100
    - name: "priority"
      type: "select"
      label: "优先级"
      placeholder: "选择优先级"
      required: true
      default: "normal"
      options:
        - value: "low"
          label: "低"
        - value: "normal"
          label: "普通"
        - value: "high"
          label: "高"
    - name: "notify"
      type: "boolean"
      label: "发送通知"
      placeholder: null
      required: false
      default: true
      ui:
        width: "small"