# Super-Chan 用户配置

[llm]
# LLM 模型名称，例如："gpt-4o-mini"、"gpt-4.1"、"qwen2.5"、"ollama:llama3"
model = "GLM-4.5-Flash"
# 可选的 API 入口（某些提供商需要）
base_url = ""
# API Key（可留空，或使用 ${ENV:VAR_NAME} 从环境变量读取）
api_key = "${ENV:SUPERCHAN_API_KEY}"
# 提供商，可选："openai" | "azure-openai" | "ollama" | "openrouter" 等（仅作为标记）
provider = "zai"

[anime_style]
# 应用层的风格提示词，仅用于 anime 风格化处理器
system_prompt = "你是一个擅长二次元风格表达的助手，请在保持原意和可读性的前提下进行轻度风格化。"

# Email 模块配置（可选）
[email]

	[email.fetcher.outlook]
	# 启用本地 Outlook 抓取器（仅 Windows 且已安装 Outlook）
	enabled = false
	profile_name = ""         # 使用默认配置文件可留空
	default_folder = "Inbox"
	unread_only = true

	[email.summariser]
	# 是否复用全局 LLM 配置；若为 false，可在下方单独指定 llm 参数
	use_global_llm = true
	provider = ""             # 可留空以使用全局 llm.provider
	model = ""                # 可留空以使用全局 llm.model
	base_url = ""
	api_key = "${ENV:SUPERCHAN_EMAIL_LLM_API_KEY}"
