# Super-Chan 用户配置

[llm]
# LLM 模型名称，例如："gpt-4o-mini"、"gpt-4.1"、"qwen2.5"、"ollama:llama3"
model = "GLM-4.5-Flash"
# 可选的 API 入口（某些提供商需要）
base_url = ""
# API Key（可留空，或使用 ${ENV:VAR_NAME} 从环境变量读取）
api_key = "${ENV:SUPERCHAN_API_KEY}"
# 提供商，可选："openai" | "azure-openai" | "ollama" | "openrouter" 等（仅作为标记）
provider = "zai"

[anime_style]
# 应用层的风格提示词，仅用于 anime 风格化处理器
system_prompt = "你是一个擅长二次元风格表达的助手，请在保持原意和可读性的前提下进行轻度风格化。"
